language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FRAMEWORK_NAME=Toolbelt
  matrix:
  - DESTINATION="OS=10.0,name=iPhone 5" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 5S" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 6" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 6 Plus" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 6S" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 6S Plus" SCHEME="Toolbelt iOS" SDK=iphonesimulator10.0
  - DESTINATION="arch=x86_64" SCHEME="Toolbelt Mac" SDK=macosx10.12
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- brew update
- brew install carthage
before_script:
- carthage bootstrap
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -project Toolbelt/Toolbelt.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination
  "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild -project Toolbelt/Toolbelt.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination
  "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: JCs+s0PfMUVDrku4NJ2bkzaa1ABR8gENmNftIGuHlu+ibTobn5EHSMVbgIVZOVTZtLNJy7Edp0BCwsRo3Jui8RhyKPbFYY1auZxxEZZLXX9+3bIhAiddoG7CsAtuPaQv3VeckTYGlNdVle7MMck/+I1HnCBUs68WhJjfEuxNiYR3+jb3RTJ32LGvB5f2E52zomfzz749M4D026UgadkaJp/dnd9YAfU6/pBb/lpC654/+PMXssdbslaVZJiP2jL/dRk1LXUDVFmNj+EstZlJp3hULkuv4K70wNOG4lnbKzmLZKobV3kk0ZlIYTSPllG6Xw0LPkZ6yuPN46HbfuKYZLej+MabpPzxcgPrNNsvULh+PBlqon8XweugjnAO6LAQsHBgkZezrSY9R3xT7w5Ji1aFMKgM4V2ihubplgz0G0TpEb1NkyfSjZ821h3N+xvfOkPj8ZASPb7YDzstQ+urOJ9rFVTQjZopqTtaNKzQAKU4x1kC3Z5+v3amjJ3skltZN1bqElEV3B/yhdaDUXQTA8pgKJfjVh/UE1cc7mNb8TPzmbduYbw+cEHAars73XeaNSoxQD0ZbRSynXXWlY5eBze+7/U5vE3zJXyhfPpyuIRVBZ7Lvk3i5qaRYBH9u182AkVA1BDgBtx87fMc5Zu6js70EtZsCNm/POGAeLW7Fr8=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: alexanderedge/Toolbelt
    tags: true
