language: objective-c
osx_image: xcode7
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Toolbelt iOS" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Toolbelt iOS" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Toolbelt iOS" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Toolbelt iOS" SDK=iphonesimulator9.0
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Toolbelt iOS" SDK=iphonesimulator9.0
    - DESTINATION="arch=x86_64" SCHEME="Toolbelt Mac" SDK=macosx10.11
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Alamofire.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project Alamofire.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c